# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/db_models.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/db_models.proto\x12\rsocialnetwork\"f\n\x04Post\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x18\n\x10original_post_id\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"L\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rpassword_hash\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\")\n\x0bUserFollows\x12\x1a\n\x12\x66ollowing_user_ids\x18\x02 \x03(\t\"\x1e\n\tUserPosts\x12\x11\n\tposts_ids\x18\x02 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.db_models_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POST']._serialized_start=40
  _globals['_POST']._serialized_end=142
  _globals['_USER']._serialized_start=144
  _globals['_USER']._serialized_end=220
  _globals['_USERFOLLOWS']._serialized_start=222
  _globals['_USERFOLLOWS']._serialized_end=263
  _globals['_USERPOSTS']._serialized_start=265
  _globals['_USERPOSTS']._serialized_end=295
# @@protoc_insertion_point(module_scope)
