# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: proto/follow_service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import proto.follow_service_pb2


class FollowServiceBase(abc.ABC):

    @abc.abstractmethod
    async def FollowUser(self, stream: 'grpclib.server.Stream[proto.follow_service_pb2.FollowUserRequest, proto.follow_service_pb2.FollowUserResponse]') -> None:
        pass

    @abc.abstractmethod
    async def UnfollowUser(self, stream: 'grpclib.server.Stream[proto.follow_service_pb2.UnfollowUserRequest, proto.follow_service_pb2.UnfollowUserResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetFollowing(self, stream: 'grpclib.server.Stream[proto.follow_service_pb2.GetFollowingRequest, proto.follow_service_pb2.GetFollowingResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/socialnetwork.FollowService/FollowUser': grpclib.const.Handler(
                self.FollowUser,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.follow_service_pb2.FollowUserRequest,
                proto.follow_service_pb2.FollowUserResponse,
            ),
            '/socialnetwork.FollowService/UnfollowUser': grpclib.const.Handler(
                self.UnfollowUser,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.follow_service_pb2.UnfollowUserRequest,
                proto.follow_service_pb2.UnfollowUserResponse,
            ),
            '/socialnetwork.FollowService/GetFollowing': grpclib.const.Handler(
                self.GetFollowing,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.follow_service_pb2.GetFollowingRequest,
                proto.follow_service_pb2.GetFollowingResponse,
            ),
        }


class FollowServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.FollowUser = grpclib.client.UnaryUnaryMethod(
            channel,
            '/socialnetwork.FollowService/FollowUser',
            proto.follow_service_pb2.FollowUserRequest,
            proto.follow_service_pb2.FollowUserResponse,
        )
        self.UnfollowUser = grpclib.client.UnaryUnaryMethod(
            channel,
            '/socialnetwork.FollowService/UnfollowUser',
            proto.follow_service_pb2.UnfollowUserRequest,
            proto.follow_service_pb2.UnfollowUserResponse,
        )
        self.GetFollowing = grpclib.client.UnaryUnaryMethod(
            channel,
            '/socialnetwork.FollowService/GetFollowing',
            proto.follow_service_pb2.GetFollowingRequest,
            proto.follow_service_pb2.GetFollowingResponse,
        )
