# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import follow_service_pb2 as proto_dot_follow__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/follow_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class FollowServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FollowUser = channel.unary_unary(
                '/socialnetwork.FollowService/FollowUser',
                request_serializer=proto_dot_follow__service__pb2.FollowUserRequest.SerializeToString,
                response_deserializer=proto_dot_follow__service__pb2.FollowUserResponse.FromString,
                _registered_method=True)
        self.UnfollowUser = channel.unary_unary(
                '/socialnetwork.FollowService/UnfollowUser',
                request_serializer=proto_dot_follow__service__pb2.UnfollowUserRequest.SerializeToString,
                response_deserializer=proto_dot_follow__service__pb2.UnfollowUserResponse.FromString,
                _registered_method=True)
        self.GetFollowing = channel.unary_unary(
                '/socialnetwork.FollowService/GetFollowing',
                request_serializer=proto_dot_follow__service__pb2.GetFollowingRequest.SerializeToString,
                response_deserializer=proto_dot_follow__service__pb2.GetFollowingResponse.FromString,
                _registered_method=True)


class FollowServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FollowUser(self, request, context):
        """Follow a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnfollowUser(self, request, context):
        """Unfollow a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFollowing(self, request, context):
        """Get the list of users followed by a specific user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FollowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FollowUser': grpc.unary_unary_rpc_method_handler(
                    servicer.FollowUser,
                    request_deserializer=proto_dot_follow__service__pb2.FollowUserRequest.FromString,
                    response_serializer=proto_dot_follow__service__pb2.FollowUserResponse.SerializeToString,
            ),
            'UnfollowUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UnfollowUser,
                    request_deserializer=proto_dot_follow__service__pb2.UnfollowUserRequest.FromString,
                    response_serializer=proto_dot_follow__service__pb2.UnfollowUserResponse.SerializeToString,
            ),
            'GetFollowing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFollowing,
                    request_deserializer=proto_dot_follow__service__pb2.GetFollowingRequest.FromString,
                    response_serializer=proto_dot_follow__service__pb2.GetFollowingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'socialnetwork.FollowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('socialnetwork.FollowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FollowService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FollowUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/socialnetwork.FollowService/FollowUser',
            proto_dot_follow__service__pb2.FollowUserRequest.SerializeToString,
            proto_dot_follow__service__pb2.FollowUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnfollowUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/socialnetwork.FollowService/UnfollowUser',
            proto_dot_follow__service__pb2.UnfollowUserRequest.SerializeToString,
            proto_dot_follow__service__pb2.UnfollowUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFollowing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/socialnetwork.FollowService/GetFollowing',
            proto_dot_follow__service__pb2.GetFollowingRequest.SerializeToString,
            proto_dot_follow__service__pb2.GetFollowingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
