# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/posts_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import db_models_pb2 as proto_dot_db__models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/posts_service.proto\x12\rsocialnetwork\x1a\x15proto/db_models.proto\"5\n\x11\x43reatePostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"7\n\x12\x43reatePostResponse\x12!\n\x04post\x18\x01 \x01(\x0b\x32\x13.socialnetwork.Post\"!\n\x0eGetPostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\"4\n\x0fGetPostResponse\x12!\n\x04post\x18\x01 \x01(\x0b\x32\x13.socialnetwork.Post\"K\n\rRepostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x18\n\x10original_post_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"3\n\x0eRepostResponse\x12!\n\x04post\x18\x01 \x01(\x0b\x32\x13.socialnetwork.Post\"&\n\x13GetUserPostsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\":\n\x14GetUserPostsResponse\x12\"\n\x05posts\x18\x01 \x03(\x0b\x32\x13.socialnetwork.Post\"$\n\x11\x44\x65letePostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\"\x14\n\x12\x44\x65letePostResponse2\x9d\x03\n\x0bPostService\x12Q\n\nCreatePost\x12 .socialnetwork.CreatePostRequest\x1a!.socialnetwork.CreatePostResponse\x12H\n\x07GetPost\x12\x1d.socialnetwork.GetPostRequest\x1a\x1e.socialnetwork.GetPostResponse\x12\x45\n\x06Repost\x12\x1c.socialnetwork.RepostRequest\x1a\x1d.socialnetwork.RepostResponse\x12Q\n\nDeletePost\x12 .socialnetwork.DeletePostRequest\x1a!.socialnetwork.DeletePostResponse\x12W\n\x0cGetUserPosts\x12\".socialnetwork.GetUserPostsRequest\x1a#.socialnetwork.GetUserPostsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.posts_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPOSTREQUEST']._serialized_start=67
  _globals['_CREATEPOSTREQUEST']._serialized_end=120
  _globals['_CREATEPOSTRESPONSE']._serialized_start=122
  _globals['_CREATEPOSTRESPONSE']._serialized_end=177
  _globals['_GETPOSTREQUEST']._serialized_start=179
  _globals['_GETPOSTREQUEST']._serialized_end=212
  _globals['_GETPOSTRESPONSE']._serialized_start=214
  _globals['_GETPOSTRESPONSE']._serialized_end=266
  _globals['_REPOSTREQUEST']._serialized_start=268
  _globals['_REPOSTREQUEST']._serialized_end=343
  _globals['_REPOSTRESPONSE']._serialized_start=345
  _globals['_REPOSTRESPONSE']._serialized_end=396
  _globals['_GETUSERPOSTSREQUEST']._serialized_start=398
  _globals['_GETUSERPOSTSREQUEST']._serialized_end=436
  _globals['_GETUSERPOSTSRESPONSE']._serialized_start=438
  _globals['_GETUSERPOSTSRESPONSE']._serialized_end=496
  _globals['_DELETEPOSTREQUEST']._serialized_start=498
  _globals['_DELETEPOSTREQUEST']._serialized_end=534
  _globals['_DELETEPOSTRESPONSE']._serialized_start=536
  _globals['_DELETEPOSTRESPONSE']._serialized_end=556
  _globals['_POSTSERVICE']._serialized_start=559
  _globals['_POSTSERVICE']._serialized_end=972
# @@protoc_insertion_point(module_scope)
