# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/users_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import db_models_pb2 as proto_dot_db__models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/users_service.proto\x12\rsocialnetwork\x1a\x15proto/db_models.proto\"\"\n\x0eGetUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"4\n\x0fGetUserResponse\x12!\n\x04user\x18\x01 \x01(\x0b\x32\x13.socialnetwork.User\"4\n\x0f\x45\x64itUserRequest\x12!\n\x04user\x18\x01 \x01(\x0b\x32\x13.socialnetwork.User\"\x12\n\x10\x45\x64itUserResponse2\xa8\x01\n\x0bUserService\x12J\n\x07GetUser\x12\x1d.socialnetwork.GetUserRequest\x1a\x1e.socialnetwork.GetUserResponse\"\x00\x12M\n\x08\x45\x64itUser\x12\x1e.socialnetwork.EditUserRequest\x1a\x1f.socialnetwork.EditUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.users_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERREQUEST']._serialized_start=67
  _globals['_GETUSERREQUEST']._serialized_end=101
  _globals['_GETUSERRESPONSE']._serialized_start=103
  _globals['_GETUSERRESPONSE']._serialized_end=155
  _globals['_EDITUSERREQUEST']._serialized_start=157
  _globals['_EDITUSERREQUEST']._serialized_end=209
  _globals['_EDITUSERRESPONSE']._serialized_start=211
  _globals['_EDITUSERRESPONSE']._serialized_end=229
  _globals['_USERSERVICE']._serialized_start=232
  _globals['_USERSERVICE']._serialized_end=400
# @@protoc_insertion_point(module_scope)
